		TITLE	addi (integer, integer):integer - 12 Sep 87 - MT
		SUBTTL	'Integer addition'
;
		INCLUDE	SYMBOLS
		DEFB	'%%ADDI 2.0 - 10 Sep 26%%'
;
;-- Function to add two 16-bit integers.
;
;-- This program is free software: you can redistribute it and/or modify it
;   under  the terms of the GNU General Public License as published by  the
;   Free Software Foundation, either version 3 of the License, or (at  your
;   option) any later version.
;
;   This  program  is distributed in the hope that it will be  useful,  but
;   WITHOUT   ANY   WARRANTY;  without  even  the   implied   warranty   of
;   MERCHANTABILITY  or  FITNESS  FOR A PARTICULAR  PURPOSE.  See  the  GNU
;   General Public License for more details.
;
;   You should have received a copy of the GNU General Public License along
;   with this program.  If not, see <http://www.gnu.org/licenses/>.
;
;   12 Sep 87	1.0   - Initial version - MT
;   10 Sep 26	2.0   - Modified  to use call by value rather than call  by
;                       reference - MT
;
;   addi (integer, integer):integer
;
;   Add two 16 bit integer values in HL and DE and return the result in HL.
;
;   Returns success/fail in A.
;
ADDI::		FUNCTION		; Return value in HL.
		XOR	A		; Clear carry.
		ADC     HL,DE 
		RET	PO              ; No overflow, status is zero.
		CPL			; Set status bits.
		RET
;
		END
