		TITLE	cmpi (integer, integer) - 12 Sep 87 - MT
		SUBTTL	'Compare integer values'
;
		INCLUDE	SYMBOLS
		DEFB	'%%CMPI 2.0 - 10 Sep 26%%'
;
;-- Procedure to compare to 16-bit integers.
;
;-- This program is free software: you can redistribute it and/or modify it
;   under  the terms of the GNU General Public License as published by  the
;   Free Software Foundation, either version 3 of the License, or (at  your
;   option) any later version.
;
;   This  program  is distributed in the hope that it will be  useful,  but
;   WITHOUT   ANY   WARRANTY;  without  even  the   implied   warranty   of
;   MERCHANTABILITY  or  FITNESS  FOR A PARTICULAR  PURPOSE.  See  the  GNU
;   General Public License for more details.
;
;   You should have received a copy of the GNU General Public License along
;   with this program.  If not, see <http://www.gnu.org/licenses/>.
;
;   12 Sep 87	1.0   - Initial version - MT
;   10 Sep 26	2.0   - Modified  to use call by value rather than call  by
;                       reference - MT
;
;   cmpi (integer, integer):integer
;
;   Subtract two 16 bit integer values in HL and DE returning the result in 
;   HL.
;
;   Returns success/fail in A.
;
CMPI::		PROCEDURE		; Does not return a value.
		XOR	A		; Clear carry.
		SBC	HL,DE 		; Subtract DE from HL.
		JP	PE,M$Overflow	; No overflow, status is zero.
		JP	M,M$Less_Than	; If sign is negative HL < DE 
		RET			; else HL >= DE.
M$Overflow:	JP	P,M$Less_Than	; Overflow inverts result thus if sign is positive DE < HL.
		RET			; else HL > DE.
M$Less_Than:	CPL			; Clear status bits in indicate HL < DE.
		RET
;
		END
