		TITLE	negi (integer):integer - 12 Sep 87 - MT
		SUBTTL	'Change sign'
;
		INCLUDE	SYMBOLS
		DEFB	'%%NEGI 2.0 - 07 Sep 26%%'
;
;-- Function to negate an 16-bit integer.
;
;-- This program is free software: you can redistribute it and/or modify it
;   under  the terms of the GNU General Public License as published by  the
;   Free Software Foundation, either version 3 of the License, or (at  your
;   option) any later version.
;
;   This  program  is distributed in the hope that it will be  useful,  but
;   WITHOUT   ANY   WARRANTY;  without  even  the   implied   warranty   of
;   MERCHANTABILITY  or  FITNESS  FOR A PARTICULAR  PURPOSE.  See  the  GNU
;   General Public License for more details.
;
;   You should have received a copy of the GNU General Public License along
;   with this program.  If not, see <http://www.gnu.org/licenses/>.
;
;   12 Sep 87	1.0   - Initial version - MT
;   07 Sep 26	      - Modified  to use call by value rather than call  by
;                       reference - MT
;
;   negi (integer);
;
;   Returns the negative value of the 16 bit integer in HL.
;
;   Checks for overflow (-32768) and returns success/fail in A.
;
NEGI::		FUNCTION		; Return value in HL.
		XOR	A		; Clear carry, needed for subtract.
		LD	D,A
		LD	E,A
		EX	DE,HL
		SBC	HL,DE           ; Subtract HL from zero.
		RET	PO              ; No overflow, return zero.
		CPL			; Set status bits.
		RET
;
		END
