		TITLE	RANDOM - 20 Jun 92 - MT
		SUBTTL	'Display a list of random numbers'
;
		INCLUDE SYMBOLS
		VERSION 'RANDOM 3.3 - 24 Jan 21'
;		      
		USING	RNDI
		USING	PUTC, PUTI,
		USING	INITF, OPENF, CLOSEF, WRITEF, BDOS
;
;-- Generates 500,000 random numbers.
;
;-- This program is free software: you can redistribute it and/or modify it
;   under  the terms of the GNU General Public License as published by	the
;   Free Software Foundation, either version 3 of the License, or (at  your
;   option) any later version.
;
;   This  program  is distributed in the hope that it will be  useful,	but
;   WITHOUT   ANY   WARRANTY;  without	even  the   implied   warranty	 of
;   MERCHANTABILITY  or	 FITNESS  FOR A PARTICULAR  PURPOSE.  See  the	GNU
;   General Public License for more details.
;
;   You should have received a copy of the GNU General Public License along
;   with this program.	If not, see <http://www.gnu.org/licenses/>.
;
;** 20 Jun 92	1.0   - Initial version - MT
;
;**  6 Jun 87         -	Order of parameters reversed - MT
;
;** 19 Oct 89         -	Prints a table of values - MT
;
;** 25 Dec 20	2.0   -	Changed	 code to pass parameters to rndi() by value
;			and not by reference - MT
;
;** 25 Dec 20	3.0   -	Updated the formatting and changed the filenames to 
;			use the current symbol definitions - MT
;
;** 25 Dec 20         -	Removed text messages - MT
;
;** 08 Sep 26   3.3   -	Sets output options correctly - MT
;			Replaced spaces with tabs - MT
;
Seed:		DEFW	65537			; Prime number seed.
;
Count:		DEFW	50000			; Number of lines!
;
;
RANDOM:		PROGRAM	Output
		LD	L,Asc$Plus		; Display a plus sign in positive values.
		LD	H,TRUE			; Set flag in PUTI to Display leading zeros.
		LD	(PUTI## -2), HL
;
		LD	HL,(Seed)		; Get seed in HL..
		PUSH	HL			; Save value on stack.
Line:		LD	B,10			; Number of columns.
Column:		POP	HL			; Restore value from stack.
		CALL	RNDI##			; Returns new random number in HL.
		EX	DE,HL			; Put number in DE
		LD	HL,Output		; and print it.
		CALL	PUTI##
		PUSH	DE			; Save new value on stack.
		LD	DE,Asc$TAB		; Print a tab
		CALL	PUTC##
		DEC	B
		JR	NZ,Column
		PUSH	HL			; Save file handle
		LD	HL,(Count)		; Decrement the count.
		DEC	HL
		LD	(Count),HL
		LD	A,L
		OR	H
		POP	HL			; Restore file handle.
		JR	Z,Done
		LD	DE,Asc$CR		; Print CR/LF.
		CALL	PUTC##
		LD	DE,Asc$LF
		CALL	PUTC##
		JR	Line			; Print next line
Done:		POP	DE			; Restore the stack and exit.
		LD	DE,Asc$CR		; Print CR/LF.
		CALL	PUTC##
		LD	DE,Asc$LF
		CALL	PUTC##
		RET
;
		END	RANDOM
